version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --parameters parameters.json \
              --stack-name udacity_complete_infra
workflows:
  my_workflow:
    jobs:
      - create_infrastructure